#!/usr/bin/env python3

import argparse
from commands.init import init
from commands.add import add
from commands.status import status
from commands.commit import commit
from commands.diff import diff

def main():
    parser = argparse.ArgumentParser(description='Initialize a new goku repository')
    subparsers = parser.add_subparsers(dest='command')

    init_parser = subparsers.add_parser('init', help="Initialize a new Goku repository")
    init_parser.add_argument('path', nargs='?', default='.', help="Directory to initialize as a Goku repository")

    add_parser = subparsers.add_parser('add', help="Add a file to the repository")
    add_parser.add_argument('file_name', help="File to add")

    status_parser = subparsers.add_parser('status', help="Show the status of the repository")
    status_parser.set_defaults(func=status)

    commit_parser = subparsers.add_parser('commit', help="Commit changes")
    commit_parser.add_argument('-m', '--message', required=True, help="Commit message")

    diff_parser = subparsers.add_parser('diff', help="Show changes between index and working directory")
    diff_parser.set_defaults(func=diff)

    args = parser.parse_args()

    if args.command == 'init':
        init(args.path)
    elif args.command == 'add':
        add(args.file_name)
    elif args.command == 'status':
        status()
    elif args.command == 'commit':
        commit(args.message)
    elif args.command == 'diff':
        diff()
    else:
        parser.print_help()

if __name__ == '__main__':
    main()